import type { UserRole } from '../../types';

export const DEPARTMENTS: string[] = [
  'Vendas',
  'TI',
  'Suporte Técnico',
  'Sucesso do Cliente',
  'Marketing',
  'Diretoria',
  'Financeiro',
  'RH',
  'Publicidade',
  'Criação',
];

export const USER_ROLES: UserRole[] = ['Usuario', 'Gerente', 'Administrador'];

/** Cargos/Funções pré-cadastrados para o dropdown */
export const JOB_TITLES: string[] = [
  'Executivo de Contas Junior',
  'Executivo de Contas Senior 1',
  'Executivo de Contas Senior 2',
  'Executivo de Contas Pleno 1',
  'Executivo de Contas Pleno 2',
  'Analista de marketing Junior',
  'Analista de marketing Senior 1',
  'Analista de marketing Senior 2',
  'Analista de marketing Pleno 1',
  'Analista de marketing Pleno 2',
  'Customer Success pleno 3',
  'Customer Success Senior 2',
  'Customer Success Senior 3',
  'Assistente de Mkt Pleno 2',
  'Assistente de Mkt Senior 2',
  'Jornalista Pleno 1',
  'Jornalista Pleno 2',
  'Jornalista Pleno 3',
  'Jornalista Senior 1',
  'Jornalista Senior 2',
  'Jornalista Senior 3',
  'Jornalista',
  'Especialista de Marketing Digital Junior',
  'Especialista de Marketing Digital Pleno 1',
  'Especialista de Marketing Digital Pleno 2',
  'Especialista de Marketing Digital Senior 1',
  'Especialista de Marketing Digital Senior 2',
  'Analista de Inteligência Junior',
  'Analista de Inteligência Pleno 2',
  'Analista de Inteligência Pleno',
  'Analista de inteligência',
  'Analista de marketing',
  'Analistas de tecnologia da informação Pleno 2',
  'Analistas de tecnologia da informação Pleno',
  'Analistas de tecnologia da informação Senior',
  'Analistas de tecnologia da informação',
  'Assistente de customer success Jr',
  'Assistente de customer success',
  'Assistente de diretoria',
  'Assistente de Mkt Junior',
  'Assistente de Mkt Pleno',
  'Assistente de Mkt Senior',
  'Assistente de Mkt',
  'Assistente de sucesso',
  'Assistente de Vendas SDR',
  'Assistente Financeiro',
  'Auxiliar Comercial Junior',
  'Auxiliar Comercial Pleno 2',
  'Auxiliar Comercial',
  'Customer Success pleno 2',
  'Customer Success pleno',
  'Customer Success Senior',
  'Designer júnior',
  'Designer Pleno 2',
  'Designer Pleno',
  'Designer trainee B',
  'Designer trainee',
  'Diretor de Criação',
  'Executivo de Contas',
  'Gerente administrativo financeiro',
  'Gerente comercial',
  'Gerente de customer success',
  'Gerente de grandes contas',
  'Gerente de suporte técnico de TI',
  'Gerente de vendas',
  'Jornalista Pleno',
  'Jornalista Senior',
  'Suporte comercial Júnior',
  'Suporte comercial Pleno 2',
  'Suporte comercial Pleno',
  'Suporte comercial',
  'Técnico de suporte ao usuário de T.I. 2',
  'Técnico de suporte ao usuário de T.I. 3',
  'Técnico suporte ao usuário de TI',
  'Vendedor interno Júnior',
  'Vendedor interno Pleno 2',
  'Vendedor interno Pleno',
  'Vendedor interno',
];

/** Rótulos para exibição das roles na UI */
export const ROLE_LABELS: Record<UserRole, string> = {
  Usuario: 'Produto / Inventário',
  Gerente: 'Sistema',
  Administrador: 'Sistema',
};

