-- Migration 008: criar tabela cargo com cargos pré-cadastrados

CREATE TABLE IF NOT EXISTS cargo (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Inserir cargos (usar UUID() para id em cada INSERT, ou executar via backend)
INSERT IGNORE INTO cargo (id, name) VALUES
(UUID(), 'Executivo de Contas Junior'),
(UUID(), 'Executivo de Contas Senior 1'),
(UUID(), 'Executivo de Contas Senior 2'),
(UUID(), 'Executivo de Contas Pleno 1'),
(UUID(), 'Executivo de Contas Pleno 2'),
(UUID(), 'Analista de marketing Junior'),
(UUID(), 'Analista de marketing Senior 1'),
(UUID(), 'Analista de marketing Senior 2'),
(UUID(), 'Analista de marketing Pleno 1'),
(UUID(), 'Analista de marketing Pleno 2'),
(UUID(), 'Customer Success pleno 3'),
(UUID(), 'Customer Success Senior 2'),
(UUID(), 'Customer Success Senior 3'),
(UUID(), 'Assistente de Mkt Pleno 2'),
(UUID(), 'Assistente de Mkt Senior 2'),
(UUID(), 'Jornalista Pleno 1'),
(UUID(), 'Jornalista Pleno 2'),
(UUID(), 'Jornalista Pleno 3'),
(UUID(), 'Jornalista Senior 1'),
(UUID(), 'Jornalista Senior 2'),
(UUID(), 'Jornalista Senior 3'),
(UUID(), 'Jornalista'),
(UUID(), 'Especialista de Marketing Digital Junior'),
(UUID(), 'Especialista de Marketing Digital Pleno 1'),
(UUID(), 'Especialista de Marketing Digital Pleno 2'),
(UUID(), 'Especialista de Marketing Digital Senior 1'),
(UUID(), 'Especialista de Marketing Digital Senior 2'),
(UUID(), 'Analista de Inteligência Junior'),
(UUID(), 'Analista de Inteligência Pleno 2'),
(UUID(), 'Analista de Inteligência Pleno'),
(UUID(), 'Analista de inteligência'),
(UUID(), 'Analista de marketing'),
(UUID(), 'Analistas de tecnologia da informação Pleno 2'),
(UUID(), 'Analistas de tecnologia da informação Pleno'),
(UUID(), 'Analistas de tecnologia da informação Senior'),
(UUID(), 'Analistas de tecnologia da informação'),
(UUID(), 'Assistente de customer success Jr'),
(UUID(), 'Assistente de customer success'),
(UUID(), 'Assistente de diretoria'),
(UUID(), 'Assistente de Mkt Junior'),
(UUID(), 'Assistente de Mkt Pleno'),
(UUID(), 'Assistente de Mkt Senior'),
(UUID(), 'Assistente de Mkt'),
(UUID(), 'Assistente de sucesso'),
(UUID(), 'Assistente de Vendas SDR'),
(UUID(), 'Assistente Financeiro'),
(UUID(), 'Auxiliar Comercial Junior'),
(UUID(), 'Auxiliar Comercial Pleno 2'),
(UUID(), 'Auxiliar Comercial'),
(UUID(), 'Customer Success pleno 2'),
(UUID(), 'Customer Success pleno'),
(UUID(), 'Customer Success Senior'),
(UUID(), 'Designer júnior'),
(UUID(), 'Designer Pleno 2'),
(UUID(), 'Designer Pleno'),
(UUID(), 'Designer trainee B'),
(UUID(), 'Designer trainee'),
(UUID(), 'Diretor de Criação'),
(UUID(), 'Executivo de Contas'),
(UUID(), 'Gerente administrativo financeiro'),
(UUID(), 'Gerente comercial'),
(UUID(), 'Gerente de customer success'),
(UUID(), 'Gerente de grandes contas'),
(UUID(), 'Gerente de suporte técnico de TI'),
(UUID(), 'Gerente de vendas'),
(UUID(), 'Jornalista Pleno'),
(UUID(), 'Jornalista Senior'),
(UUID(), 'Suporte comercial Júnior'),
(UUID(), 'Suporte comercial Pleno 2'),
(UUID(), 'Suporte comercial Pleno'),
(UUID(), 'Suporte comercial'),
(UUID(), 'Técnico de suporte ao usuário de T.I. 2'),
(UUID(), 'Técnico de suporte ao usuário de T.I. 3'),
(UUID(), 'Técnico suporte ao usuário de TI'),
(UUID(), 'Vendedor interno Júnior'),
(UUID(), 'Vendedor interno Pleno 2'),
(UUID(), 'Vendedor interno Pleno'),
(UUID(), 'Vendedor interno');
